# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: bixby-auth 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "bixby-auth"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Chetan Sarva"]
  s.date = "2014-11-20"
  s.description = "Bixby API Auth library for both clients and servers"
  s.email = "chetan@pixelcop.net"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/api-auth.rb",
    "lib/api_auth.rb",
    "lib/api_auth/base.rb",
    "lib/api_auth/errors.rb",
    "lib/api_auth/headers.rb",
    "lib/api_auth/helpers.rb",
    "lib/api_auth/railtie.rb",
    "lib/api_auth/request_drivers.rb",
    "lib/api_auth/request_drivers/action_controller.rb",
    "lib/api_auth/request_drivers/action_dispatch.rb",
    "lib/api_auth/request_drivers/bixby_request.rb",
    "lib/api_auth/request_drivers/curb.rb",
    "lib/api_auth/request_drivers/httpi.rb",
    "lib/api_auth/request_drivers/net_http.rb",
    "lib/api_auth/request_drivers/rack.rb",
    "lib/api_auth/request_drivers/rest_client.rb",
    "lib/bixby-auth.rb",
    "spec/api_auth_spec.rb",
    "spec/application_helper.rb",
    "spec/fixtures/upload.png",
    "spec/headers_spec.rb",
    "spec/helpers_spec.rb",
    "spec/railtie_spec.rb",
    "spec/spec_helper.rb",
    "spec/test_helper.rb",
    "test/helper.rb",
    "test/test_bixby-auth.rb"
  ]
  s.homepage = "http://github.com/chetan/bixby-auth"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.2"
  s.summary = "Bixby API Auth library"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
      s.add_development_dependency(%q<yard>, ["~> 0.7"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<bixby-common>, [">= 0"])
      s.add_development_dependency(%q<micron>, [">= 0"])
      s.add_development_dependency(%q<test_guard>, [">= 0"])
      s.add_development_dependency(%q<rb-inotify>, [">= 0"])
      s.add_development_dependency(%q<rb-fsevent>, [">= 0"])
      s.add_development_dependency(%q<rb-fchange>, [">= 0"])
      s.add_development_dependency(%q<oj>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<amatch>, [">= 0"])
      s.add_development_dependency(%q<rails>, [">= 0"])
      s.add_development_dependency(%q<activeresource>, [">= 0"])
      s.add_development_dependency(%q<rest-client>, ["~> 1.6.0"])
      s.add_development_dependency(%q<curb>, ["~> 0.8.1"])
      s.add_development_dependency(%q<httpi>, [">= 0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<yard>, ["~> 0.7"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<bixby-common>, [">= 0"])
      s.add_dependency(%q<micron>, [">= 0"])
      s.add_dependency(%q<test_guard>, [">= 0"])
      s.add_dependency(%q<rb-inotify>, [">= 0"])
      s.add_dependency(%q<rb-fsevent>, [">= 0"])
      s.add_dependency(%q<rb-fchange>, [">= 0"])
      s.add_dependency(%q<oj>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<amatch>, [">= 0"])
      s.add_dependency(%q<rails>, [">= 0"])
      s.add_dependency(%q<activeresource>, [">= 0"])
      s.add_dependency(%q<rest-client>, ["~> 1.6.0"])
      s.add_dependency(%q<curb>, ["~> 0.8.1"])
      s.add_dependency(%q<httpi>, [">= 0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<yard>, ["~> 0.7"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<bixby-common>, [">= 0"])
    s.add_dependency(%q<micron>, [">= 0"])
    s.add_dependency(%q<test_guard>, [">= 0"])
    s.add_dependency(%q<rb-inotify>, [">= 0"])
    s.add_dependency(%q<rb-fsevent>, [">= 0"])
    s.add_dependency(%q<rb-fchange>, [">= 0"])
    s.add_dependency(%q<oj>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<amatch>, [">= 0"])
    s.add_dependency(%q<rails>, [">= 0"])
    s.add_dependency(%q<activeresource>, [">= 0"])
    s.add_dependency(%q<rest-client>, ["~> 1.6.0"])
    s.add_dependency(%q<curb>, ["~> 0.8.1"])
    s.add_dependency(%q<httpi>, [">= 0"])
  end
end

